### ISSUE TITLE
Package httplib not found!

### ISSUE THREAD

**Issue by rampyg** [disqus/disqus-python#25]
I tried to install & run the first lines of code. Got the `ImportError: No module named 'httplib'` for lines in `__init__.py` of disqusapi. When searched online, found that there is no `httplib` anymore. There is a newer package called `httplib2` and `httplib` has been renamed to `http.client` in Python 3 [Source@StackOverFlow](http://stackoverflow.com/questions/13778252/import-httplib-importerror-no-module-named-httplib). Should the code be updated to reflect the changes?

**Comment by Fluxx** [comment]
@rampyg are you trying to install this with Python 3?

**Comment by rampyg** [comment]
@Fluxx Yup!

**Comment by Fluxx** [comment]
Ah - disqus/python doesn't support Python 3, so that would explain your issue.  If you want to take a stab at making it Python 3 compatible go for it.

**Comment by mattrobenolt** [comment]
The next release will be python 3 compatible, fwiw. We have a couple outstanding issues left and we'll be good.

**Comment by rampyg** [comment]
Thanks @mattrobenolt for the info. Hoping the release would be soon...
Would have tried, @Fluxx. But now that work is already on, wouldn't want to duplicate! :+1:
