### ISSUE TITLE
Invalid API Key due to missing Content-Type

### ISSUE THREAD

**Issue by jvcop** [disqus/disqus-python#32]
A couple of hours ago, my calls to the Disqus API started to fail due to **Invalid API key**.  Interestingly, I couldn't reproduce this with cURL or the requests library. So I had a closer look at the requests and noticed that the client does not specify the `Content-Type` header. Setting it to `application/x-www-form-urlencoded` resolves the issue. I guess something in the backend has changed lately (e.g., the default content type).

I'm not sure whether or not this project is still maintained. The fix is trivial but if a pull request is preferred, I will gladly submit one.

**Comment by tail** [comment]
Thanks for the report @jvcop.  We've identified the issue that was causing the issue on our backend and have reverted the change.  Seems like we should still look into adding the `Content-Type` header for requests.

**Comment by jvcop** [comment]
Thanks for the quick response :) Please let me know if I can help.

**Comment by tail** [comment]
We've resolved the issue on our end and fixed the issue for future versions in #33.
